config/routes.rb
Rails.application.routes.draw do

 

  resources :food_items 
  resources :orders

  get 'home/index'

  get 'menu' => 'home#menu'

  

  get 'contact_us' => 'home#contact_us'

	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  validates :name, :price, presence: true
  has_many :orders

  def image_url_or_default
		image_url.presence || "loremflickr.com/320/240/#{name.gsub('', '')}"

		if !image_url.nil? && !image_url.blank?
			image_url
		else
			"loremflickr.com/320/240/#{name.gsub('', '')}"
	end
end

	def self.search(search)
		where("name ILIKE ?", "%#{search}%")
	end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :quantity, presence: true, numericality: true
end

app/models/section.rb
class Section < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  has_many :food_items

  def self.generate_defaults
    %w(Breakfast Lunch Dinner Drinks).each do |name|
      Section.find_or_create_by(name: name)
    end
  end
end

	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to menu_path, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }

      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index 
    
  end


def menu
	@sections = Section.all

    if params[:section_id].present?
      @current_section = Section.find(params[:section_id])
    end

    if @current_section.present?
      @all_food_items = @current_section.food_items.all
    else
      @all_food_items = FoodItem.all
    end

    if params[:sort_column].present?
      if params[:sort_column] == 'Name'
        if params[:sort_direction] == 'ascending'
          @all_food_items = FoodItem.order(:name)
        else
          @all_food_items = FoodItem.order(name: :desc)
        end
      else
        if params[:sort_direction] == 'ascending'
          @all_food_items = FoodItem.order(:price)
        else
          @all_food_items = FoodItem.order(price: :desc)
        end
      end
    end

    if params[:search].present?
      @all_food_items = @all_food_items.search(params[:search])
    end
  end
     
  def contact_us
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


 def new
 	@item = FoodItem.find(params[:food_item_id])
 	@order = Order.new(food_item: @item)
 end

 def create
 	@item = FoodItem.find(params[:food_item_id])
 	@order = @item.orders.build order_params
 	

 	if @order.save
 		flash[:success] = "Thank you for your order"
 		render '_order_end'
 		
 	else
 		render 'new'
 end
end

 def order_params
 	params.require(:order).permit(:quantity, :name, :address, :phone, :price)
 end
 
 def update
	if @order.save
		flash[:success] = "Thank you for your order."
		redirect_to menu_path, flash: {success: "Thank you for your order."}
	else
		render 'new'
 	end	
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<div class="food-item col-xs-10 col-xs-offset-1">
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :section_id %>
    <%= f.select :section_id, Section.all.map{|e| [e.name, e.id]}, {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>



<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="booyah-box col-xs-6">
  <h1><%= @food_item.name %></h1>
  <i><%= @food_item.description %></i>
  <br/><br/>
  <p><%= @food_item.price %></p>
  <p><%= image_tag @food_item.image_url, :size => "320x240" %></p>
</div>

  



  



  



  

app/views/home/contact_us.html.erb
<div class="container">
<div class="row">
<br />
	<div class="contact col-md-6">
		<h1 class="contact_us">Contact Us</h1>
		<address class="address">
			<strong>Food N'Stuff</strong> <br />
			3628 Shaffer Rd., <br />
			Rock Creek, Ohio, 44084 <br />
			(440) 563-5998
		</address>
	</div>
	<div class="map col-md-6">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2981.4323413784623!2d-80.88139548471065!3d41.64639998786116!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x883186b781c7dc4f%3A0x8c776c034126619e!2s3628+Shaffer+Rd%2C+Rock+Creek%2C+OH+44084!5e0!3m2!1sen!2s!4v1497782579031" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>
</div>

app/views/home/index.html.erb
<br />
<br />

<div class="frosty col-xs-6 col-xs-offset-3 text-center">

	<%= link_to "Menu", menu_path, class: 'btn btn-success' %>
	

	</div>
</div>

app/views/home/menu.html.erb
<div class="container">
<br />


<div class="search-bar">

  <form class="form" align="right">
    <%= form_tag(menu_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Find your food" %>
        <%= submit_tag "Search", :name => nil, :style => "color:blue;"  %>
    <% end %>
  </form>
</div>



<div class="btn btn-group">
	<% @sections.each do |section| %>
	<%= link_to section.name, menu_path(section_id: section.id), class: "btn #{params[:section_id] == section.id.to_s ? 'btn-primary' : 'btn-secondary'}" %>
<% end %>
</div>

<div class="card card-block">
	<%= form_tag nil, method: 'get' do %>
	 <%= hidden_field_tag :section, params[:section] %>
		<div class="form-inline">
			<div class="form-group">
				
			<%= select_tag :sort_column, options_for_select([['Name', 'name'], ['Price', 'price']]), class: 'form-control' %>
			<%= select_tag :sort_direction, options_for_select([['Ascending', 'asc'], ['Descending', 'dsc']]), class: "form-control" %> <br />
			<%= submit_tag "sort", class: 'btn btn-primary' %>
		</div>
<% end %>
</div>
<div class="food-items col-xs-10 col-xs-offset-1">
<% if @all_food_items.present? %>
	<table class="table">
			<% @all_food_items.each do |item| %>
			<tr>
				<td><%= link_to item.name, food_item_path(item.id) %></td>
				<td><%= number_to_currency item.price %></td>
				<td><%= item.description %></td>
				<td><%= link_to "Add to order", new_order_path(food_item_id: item.id) %> 
				<td><%= image_tag item.image_url_or_default, :size => "200x150" %></td> 
			</tr>
		<% end %>
		</div>
  </table>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>">Food N'Stuff</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"> 
    <li>
      <%= link_to contact_us_path do %>
      <i class="fa fa-plus-circle">Contact Us</i>
      <% end %>
    </li>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="flex-content-container">
    <%= render 'layouts/navbar' %>
    	<div class="container">
      	<%= yield %>
      </div>
  </div>
    <div id="footer">
      <div class="container">
        <br />
        <div class="col-12 col-sm-3">
        erik.young@rmit.edu.vn
        <br />
        One Kendall Square
        <br />
        Cambridge MA, 02113
      </div>
    </div>
          
                

  </body>
</html>

app/views/orders/_order_end.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Thank you for your order</h1>
	<h2>Order information</h2>
	<p><strong>Item name: </strong><%= @order.food_item.name %></p>
	<p><strong>Total price: </strong><%= @order.food_item.price * @order.quantity %> </p>
	<h2>Customer information</h2>
	<p><strong>Name: </strong><%= @order.name %>
	<p><strong>Address: </strong><%= @order.address %>
	<p><strong>Phone: </strong><%= @order.phone %></p>
	<p><strong>Order at: </strong><%= @order.created_at.strftime("%A %d, %B %Y, %H:%M") %>
</div>

app/views/orders/new.html.erb
<%= simple_form_for @order, url: orders_path(food_item_id: @item.id) do |f| %>

		<div class="form-group">
			<%= f.label :quantity %>
			<%= f.number_field :quantity, class: 'form-control' %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
		<div class="form-group">
			<%= f.label :phone %>
			<%= f.text_field :phone, class: 'form-control' %>
		<div class="form-group">
			<%= f.label :address %>
			<%= f.text_field :address, class: 'form-control' %>
		</div>

		<%= f.submit nil, class: 'btn btn-primary' %>
		<% end %>

		
  
  <br />
  
	<% if @order.errors.present? %>
		<div class="alert alert-danger"><%= @order.errors.full_messages.to_sentence %></div>
		<div class="alert alert-danger"><%= @order.errors.full_messages.to_sentence %></div>
	<% end %>
	

app/views/orders/show.html.erb
<h1>thanks</h1>